[OBJECTS]
@REVISION = %u

#-----------------------------------------------------------------------#-----------------
#       Green Shell      Star             Mega Shroom      Golden Shroom
#         : Red Shell      : Blue Shell     : Bob-omb        : Bullet Bill
#         :   : Banana     :   : Thunder    :   : Blooper    :   : Thunder Cloud
#  ID     :   :   : Shroom :   :   : Fake Box   :   : POW    :   :   :  # Name
#-----------------------------------------------------------------------#-----------------
