#LEX  <<<  The first 4 characters '#LEX' are the magic for a LEX text file.
#     <<<  Don't remove them!
#
###############################################################################
#
# This is a textual representation of a LEX file. It is defined by Wiimm.
#
# Hint:
#   Set one of the options --no-header (-H) or --brief (-B) while decoding
#   to suppress this general description. The --brief option will also disable
#   info parts in the different sections.
#
