
#FF#
###############################################################################

[CANN]
# Sort order: %u

# Cannon characteristics:
#	https://wiki.tockdom.com/wiki/Template:Cannon_characteristics

#CANN#
#---------------------------------------------------
#                          Deceleration    End
# Idx    Speed     Height     Factor   Deceleration
#---------------------------------------------------
