
#FF#
###############################################################################

[CTDN]
# Sort order: %u

# This section defines various settings for game mode countdown. New settings
# are placed at the end of the binary data. Unknown data is printed as hexdump,
# so no data is lost even with old tools.

#-------------------------

# Define countdown time limits in seconds for the different engine classes.
# @TIME-LIMIT-300CC is intended for future expansions >200cc.

@TIME-LIMIT-50CC  = %3u%s
@TIME-LIMIT-100CC = %3u%s
@TIME-LIMIT-150CC = %3u%s
@TIME-LIMIT-200CC = %3u%s
@TIME-LIMIT-300CC = %3u%s

