
#FF#
###############################################################################

[HEXDUMP]
# Sort order: %u

# Unknown sections are stored as hexdump to keep the data. The address field
# and the ASCII part are for info only and ignored on scanning.

@MAGIC = 0x%08x # %s

#HEX#
#----+------------------------------------------------------+----------------+
#addr:   data: bytes in hex  |  '(' expression ')'          : ASCII of data  :
#----+------------------------------------------------------+----------------+
