
#FF#
###############################################################################

[DEV1]
# Sort order: %u

# This section defines various settings for LE-CODE developers. It is
# recognized only if LPAR setting DEVELOPER-MODES is set to a value >0.

#-------------------------

# LE-CODE recognized this section only if ENABLED is >0.

@ENABLED = %u

# Define 3 developer modes. The usage changes frequently.

@MODE1 = %u
@MODE2 = %u
@MODE3 = %u

