
#FF#
###############################################################################

[SETUP]
# This is the general setup and info section. Some parameters are preceeded by
# a hash ('#') to signal the informative only status. This section should
# always be the first one.

# Identify the tool and version, that have written this file:
TOOL     = %s
SYSTEM   = %s
VERSION  = %s
REVISION = %u
DATE     = %s

# Statistics: List of all included sections:
