
/***************************************************************************
 *                       _______ _______ _______                           *
 *                      |  ___  |____   |  ___  |                          *
 *                      | |   |_|    / /| |   |_|                          *
 *                      | |_____    / / | |_____                           *
 *                      |_____  |  / /  |_____  |                          *
 *                       _    | | / /    _    | |                          *
 *                      | |___| |/ /____| |___| |                          *
 *                      |_______|_______|_______|                          *
 *                                                                         *
 *                           Wiimms SZS Tools                              *
 *                                                                         *
 ***************************************************************************
 *                                                                         *
 *   This file is part of the SZS project.                                 *
 *   Visit https://szs.wiimm.de/ for project details and sources.          *
 *                                                                         *
 *   Copyright (c) 2011-2020 by Dirk Clemens <wiimm@wiimm.de>              *
 *                                                                         *
 ***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   See file gpl-2.0.txt or http://www.gnu.org/licenses/gpl-2.0.txt       *
 *                                                                         *
 ***************************************************************************
 *                                                                         *
 *   >>>  This file is automatically generated by './src/gen-ui.c'.  <<<   *
 *   >>>                   Do not edit this file!                    <<<   *
 *                                                                         *
 ***************************************************************************/

#include <getopt.h>
#include "ui-wbmgt.h"

//
///////////////////////////////////////////////////////////////////////////////
///////////////                  OptionInfo[]                   ///////////////
///////////////////////////////////////////////////////////////////////////////

static const InfoOption_t OptionInfo[OPT__N_TOTAL+1] =
{
    {0,0,0,0,0,0,0,0,0,0}, // OPT_NONE,

    //----- command specific options -----

    {	OPT_LONG, false, false, false, false, false, 'l', "long",
	0,
	"Print long numeric message IDs instead of alternative message names"
	" like Txx, Uxx or Mxx."
    },

    {	OPT_NO_HEADER, false, false, false, false, false, 'H', "no-header",
	0,
	"Suppress the syntax information section in BMG text files."
    },

    {	OPT_BRIEF, false, false, false, false, false, 'B', "brief",
	0,
	"If set, the information header in decoded text files is suppressed"
	" (for historical reasons same as --no-header). If set at least twice,"
	" all comments are suppressed and the output is packed without empty"
	" lines. If set 3 times, the #BMG file indentification is also"
	" suppressed."
    },

    {	OPT_DEST, false, false, false, false, true, 'd', "dest",
	"path",
	"Define a destination path (directory/file). The destination - means:"
	" write to standard output.\n"
	"  The path may contain escape sequences: %Q is replaced by the fully"
	" qualified source name. %P and %F are replaced by the source path or"
	" by the filename. %N and %E are replaced by source filename without"
	" extension or by the source extension. Finally, %T is replaced by the"
	" default extension of the destination format.\n"
	"  A '?' direct behind '%' in %E and %T conversions avoid that the"
	" same extension is used twice in row. Read"
	" https://szs.wiimm.de/opt/dest for more details."
    },

    {	OPT_DEST2, false, false, false, false, false, 'D', "DEST",
	"path",
	"Like --dest, but create the directory path automatically."
    },

    {	OPT_ESC, false, false, false, false, false, 'E', "esc",
	"char",
	"Define an alternative escape character for destination files. The"
	" default is '%'. For Windows batch files it is a good choice to set"
	" '-E$'."
    },

    {	OPT_OVERWRITE, false, false, false, false, false, 'o', "overwrite",
	0,
	"Overwrite already existing files without warning and ignore option"
	" --number."
    },

    {	OPT_NUMBER, false, false, false, false, false, 0, "number",
	0,
	"If a file already exist, append a number directly before the file"
	" extension to make the filename unique. If other numbered files"
	" already exist (ignoring case), use the maximum existing index+1."
	" --num is a short cut."
    },

    {	OPT_REMOVE_DEST, false, false, false, false, false, 'r', "remove-dest",
	0,
	"Remove already existing files before creating it. If set, --overwrite"
	" is ignored. --rm-dest is a short cut."
    },

    {	OPT_UPDATE, false, false, false, false, false, 'u', "update",
	0,
	"Update only existing files and don't create new files. If set,"
	" --overwrite and --remove-dest are ignored."
    },

    {	OPT_PRESERVE, false, false, false, false, false, 'p', "preserve",
	0,
	"Preserve file times (atime+mtime) while converting or copying files."
    },

    {	OPT_IGNORE, false, false, false, false, false, 'i', "ignore",
	0,
	"Ignore non existing source files without warning."
    },

    {	OPT_ALIGN, false, false, false, false, false, 0, "align",
	"size",
	"Define an align value for the sub sections in the archive. The value"
	" must be a power of 2 and the default value is 32 (0x20)"
    },

    {	OPT_PATCH_BMG, false, false, false, false, false, 'P', "patch-bmg",
	"mode[cond][=param]",
	"This option specifies a BMG patch mode. Some of the modes need a"
	" parameter or a file name of a BMG patch file (raw or text BMG), both"
	" separated by an equal sign. Modes with required file names are"
	" PRINT, REPLACE, INSERT, OVERWRITE, DELETE, MASK, EQUAL and NOTEQUAL."
	" Modes with text parameter are FORMAT, REGEXP and RM-REGEXP. "
	" Standalone modes are ID, ID-ALL, UNICODE, RM-ESCAPES, RM-CUPS,"
	" CT-COPY, CT-FORCE-COPY, CT-FILL, LE-COPY, LE-FORCE-COPY, LE-FILL,"
	" X-COPY, X-FORCE-COPY and X-FILL. Unique abbreviations are allowed.\n"
	"  The optional condition COND is either '?MID' or '!MID'. In case of"
	" '?MID', the patch is only applied if the message id MID already"
	" exists. In case of '!MID', the patch is only applied if the message"
	" id MID does not exists.\n"
	"  If this option is used multiple times, all patch files will be"
	" processed in the entered order. --patch is a short cut. Read"
	" https://szs.wiimm.de/opt/patch-bmg for more details."
    },

    {	OPT_MACRO_BMG, false, false, false, false, false, 0, "macro-bmg",
	"file",
	"Load a BMG file and add the messages to the macro library; already"
	" existing entries are replaced. The macro library is accessed by"
	" escape sequence \\m{MID} as fallback, if the active file has not"
	" already defined the message MID by itself."
    },

    {	OPT_FILTER_BMG, false, false, false, false, false, 0, "filter-bmg",
	"list",
	"If this option is set, the BMG messages are filtered by this list."
	" Only enabled messages are exported to the output BMG file (binary or"
	" text).\n"
	"  The parameter is a list of message ids (short MID, 'Txx' or 'Uxx'"
	" or Mxx' or hex number) or message ranges (MID:MID) or one of the"
	" keywords NONE, IDENT (=ID), PARAM, CUPS, TRACKS, ARENAS, CHAT,"
	" CTCODE (=CT), CTUPS, CTTRACKS, CTARENAS, CTREFS, LECODE (=LE),"
	" LEUPS, LETRACKS, LEARENAS, LEREFS, XCODE (=X), XUPS, XTRACKS,"
	" XARENAS, XREFS, ALLCODE, ALLUPS, ALLTRACKS, ALLARENAS, ALLREFS,"
	" GENERIC or ALL. If an element is preceded by a minus sign,  it is"
	" removed from the filter list (disabled).\n"
	"  With v2.01a, this option was renamed from --msg to the more"
	" meaningful name --filter-bmg. The old name is still available.\n"
	"  Read https://szs.wiimm.de/opt/filter-bmg for more details."
    },

    {	OPT_BMG_ENDIAN, false, false, false, false, false, 0, "endian",
	"name",
	"Force an endian for new BMG files. Accepted values are BIG or BE for"
	" big endian, LITTLE or LE for little endian and AUTO for automatic"
	" detection (default).\n"
	"  Mario Kart Wii uses big endian; the default if no other endian is"
	" defined."
    },

    {	OPT_BMG_ENCODING, false, false, false, false, false, 0, "encoding",
	"name",
	"Force an encoding for new BMG files. Accepted encoding names are"
	" CP-1252, UTF-16BE (or UTF-16), SHIFT-JIS, UTF-8 and AUTO for"
	" automatic detection (default). Same keywords without minus signs are"
	" accepted too.\n"
	"  Mario Kart Wii uses encoding UTF-16BE; the default if no other"
	" encoding is defined."
    },

    {	OPT_BMG_INF_SIZE, false, false, false, false, false, 0, "inf-size",
	"size",
	"Defines the 'INF1' size of new BMG files between 4 and 1000. The"
	" first 4 bytes of a INF1 record is an offset into the string pool and"
	" the remaining bytes the attributes. Maximal 40 attribute bytes are"
	" supported and additional bytes are assumed to be NULL. All BMG files"
	" of MKW have a size of 8."
    },

    {	OPT_BMG_MID, true, false, false, false, false, 0, "bmg-mid",
	"[mode]",
	"Control the creation of BMG section MID1. Suppress the creation, if"
	" mode is OFF. Force the creation, if mode is ON. On mode AUTO"
	" (default), the source is analysed for the decision."
    },

    {	OPT_FORCE_ATTRIB, false, false, false, false, false, 0, "force-attrib",
	"attrib",
	"Forces, that all attributes are set to this vector. See"
	" https://szs.wiimm.de/doc/bmg/attrib for the syntax."
    },

    {	OPT_DEF_ATTRIB, false, false, false, false, false, 0, "def-attrib",
	"attrib",
	"Define the default attributes for BMG files. If not set, the default"
	" attributes are estimated. On text output, strings with default"
	" attributes are printed without attribute vector. The usual default"
	" attribute for MKW is [1]. See https://szs.wiimm.de/doc/bmg/attrib"
	" for the syntax."
    },

    {	OPT_NO_ATTRIB, false, false, false, false, false, 0, "no-attrib",
	0,
	"Suppress the output of any BMG attributes if creating BMG text files."
    },

    {	OPT_X_ESCAPES, false, false, false, false, false, 0, "x-escapes",
	0,
	"Use \\x{} escapes instead of \\z{} escapes."
    },

    {	OPT_OLD_ESCAPES, false, false, false, false, false, 0, "old-escapes",
	0,
	"To be compatible with v1.43 and earlier, print 1A escape sequences"
	" with total size of >12 bytes as single words using \\x{}. Also don't"
	" use \\x{} and \\u{} with parameter lists."
    },

    {	OPT_SINGLE_LINE, false, false, false, false, false, '1', "single-line",
	0,
	"If set, don't print continuation lines for BMG text output. If set"
	" twice, print only single text lines and suppress attributes like"
	" option --no-attrib does it."
    },

    {	OPT_NO_BMG_COLORS, false, false, false, false, false, 0, "no-bmg-colors",
	0,
	"If set, suppress the output of '\\c{color}' escape sequences for"
	" colors definitions in BMG text output to be compatible with old"
	" versions of the tools."
    },

    {	OPT_BMG_COLORS, false, false, false, false, false, 0, "bmg-colors",
	0,
	"Force output of '\\c{color}' escape sequences with names, even for"
	" foreign (not MKWii) BMG files."
    },

    {	OPT_NO_BMG_INLINE, false, false, false, false, false, 0, "no-bmg-inline",
	0,
	"Print BMG attributes as separate line before the message definition"
	" to be compatible with versions until v1.39. The output for the"
	" standard value 0x01000000 is always suppressed. This was the default"
	" until v1.43."
    },

    {	OPT_EXPORT, false, false, false, false, false, 'X', "export",
	0,
	"Enable the export mode and create small and machine readable text"
	" files for easy post processing. The option works similar like -HBl11"
	" for BMG text files."
    },

    {	OPT_SECTIONS, false, false, false, false, true, 0, "sections",
	0,
	"Print in machine readable sections and parameter lines."
    },

    {0,0,0,0,0,0,0,0,0,0}, // OPT__N_SPECIFIC == 32

    //----- global options -----

    {	OPT_VERSION, false, false, false, false, false, 'V', "version",
	0,
	"Stop parsing the command line, print a version info and exit."
    },

    {	OPT_HELP, false, false, false, false, false, 'h', "help",
	0,
	"Stop parsing the command line, print a help message and exit."
    },

    {	OPT_XHELP, false, false, false, false, false, 0, "xhelp",
	0,
	"Stop parsing the command line and print a help message with all"
	" commands included. Exit after printing."
    },

    {	OPT_ALLOW_ALL, false, false, false, false, false, 0, "allow-all",
	0,
	"Usually commands accept only options with impact to the command. All"
	" other options fire a syntax error. But if --allow-all is set, all"
	" commands accept all options.\n"
	"  This makes changing the command of a long command line without"
	" removing useless options easier. It also helps to override wrong"
	" option permissions."
    },

    {	OPT_COMPATIBLE, false, false, false, false, false, 0, "compatible",
	"vers",
	"The option expects a version number (format '#.##' or 'v#.##') or a"
	" revision number (format 'r#') as parameter. If set, the tools try to"
	" create BMG and KMP text files, that are compatible to the entered"
	" version of the tools. This may override other legacy options."
    },

    {	OPT_WIDTH, false, false, false, true, false, 0, "width",
	"width",
	"Define the terminal width (number of columns) for help and some other"
	" messages and disable the automatic detection of the terminal width."
    },

    {	OPT_QUIET, false, false, false, false, false, 'q', "quiet",
	0,
	"Be quiet and print only error messages. Multiple usage is possible."
	" The impact is command dependent. In general: If set three times,"
	" different file format warnings are suppressed."
    },

    {	OPT_VERBOSE, false, false, false, false, false, 'v', "verbose",
	0,
	"Be verbose and print more progress information. Multiple usage is"
	" possible. The impact is command dependent."
    },

    {	OPT_LOGGING, false, false, false, false, false, 'L', "logging",
	0,
	"This debug option enables the logging of internal lists and maps."
    },

    {	OPT_DE, false, false, false, false, false, 0, "de",
	0,
	"Use german track and arena names."
    },

    {	OPT_COLORS, true, false, false, true, false, 0, "colors",
	"[=modus]",
	"Define the modus for colored text output. Allowed keywords are: OFF"
	" or NO-COLORS to disable colors, AUTO (default) for automatic"
	" detection, ON for automatic detection but never OFF, 8-COLORS and"
	" 256-COLORS to force 8 or 256 color support. Without parameter, ON is"
	" used.\n"
	"  AUTO will enable colorized output only for terminals. AUTO and ON"
	" use environment variable TERM to find the correct color modus.\n"
	"  If a command is prefixed by 'C-', then --color=ON is used"
	" implicitly as default."
    },

    {	OPT_NO_COLORS, false, false, false, true, false, 0, "no-colors",
	0,
	"Deactive colorized text. This is the default, if an output file is"
	" not a terminal."
    },

    {	OPT_CT_CODE, false, false, false, false, false, 0, "ct-code",
	0,
	"Enable CT-CODE support. See https://szs.wiimm.de/opt/ctcode for"
	" details."
    },

    {	OPT_LE_CODE, true, false, false, false, false, 0, "le-code",
	"[=param]",
	"Enable LE-CODE and CT-CODE support. The optional parameter is"
	" deprecated and ignored. See https://szs.wiimm.de/opt/lecode for"
	" details."
    },

    {	OPT_CHDIR, false, false, false, false, false, 0, "chdir",
	"dir",
	"Set a new working directory for all following options, for all"
	" parameters and for the command execution. This option can be used"
	" multiple times, but for parameter parsing and for command execution"
	" only the last usage is relevant. Nevertheless, '@param' values are"
	" scanned while reading the command line."
    },

    {	OPT_CONST, false, false, false, false, false, 'c', "const",
	"list",
	"Define constant values, that are used by the internal encoders and by"
	" the numeric options as predefined global variables. This option"
	" allows a conditional encoding of text files. It can be used multiple"
	" times for multiple definitions.\n"
	"  The parameter is a comma separated list of terms and a term is"
	" 'name=expression'. The expression is calculated by the text parser."
    },

    {	OPT_MAX_FILE_SIZE, false, false, false, false, false, 'M', "max-file-size",
	"size",
	"This security option defines the maximum file size for input files;"
	" larger files are ignored with a warning. The default unit is MiB and"
	" the default size is 100 MiB; that should be enough for standard"
	" usage."
    },

    {	OPT_TRACKS, false, false, false, false, false, 'T', "tracks",
	"tracks",
	"Define a new track order. A comma separated list in the format [a=]b"
	" or a:=b is expected. 'a' and 'b' are track names or slot numbers."
	" 'a' is the destination slot and 'b' the assigned track. If 'a' is"
	" omitted, the next slot is used; this means [a=]b,c,d is possible.\n"
	"  Tracks will only be exchanged so that always all tracks are"
	" assigned. But if using ':=' the new slots are assigned without"
	" exchanging and the old values are lost."
    },

    {	OPT_ARENAS, false, false, false, false, false, 'A', "arenas",
	"arenas",
	"Define a new arena order. A comma separated list in the format [a=]b"
	" or a:=b is expected. 'a' and 'b' are arena names or slot numbers."
	" 'a' is the destination slot and 'b' the assigned arena. If 'a' is"
	" omitted, the next slot is used; this means [a=]b,c,d is possible.\n"
	"  Arenas will only be exchanged so that always all arenas are"
	" assigned. But if using ':=' the new slots are assigned without"
	" exchanging and the old values are lost."
    },

    {	OPT_POINTS, false, false, false, false, false, 0, "points",
	"list",
	"This option creates the new message 3FF0 to hold a description of the"
	" versus points table. It defines a new table for the points assigned"
	" to players after a versus or room race. The parameter is a blank or"
	" comma and slash (next row) separated list with numbers (points)"
	" between 0 and 255 and the following keywords: NINTENDO, LINEAR, WIN,"
	" WIN15, WIN25 to select a predefined table; NO-BONUS, BONUS, NULL,"
	" ONE as options; N1..N12 to select the row for N players. See"
	" https://szs.wiimm.de/opt/points for details."
    },

    {	OPT_UTF_8, false, true, false, false, true, 0, "utf-8",
	0,
	"Enables UTF-8 support for filenames (default)."
    },

    {	OPT_NO_UTF_8, false, true, false, false, false, 0, "no-utf-8",
	0,
	"Disables UTF-8 support for filenames."
    },

    {	OPT_TEST, false, false, false, false, true, 't', "test",
	0,
	"Run in test mode, modify nothing.\n"
	">>> USE THIS OPTION IF UNSURE! <<<"
    },

    {	OPT_FORCE, false, false, false, false, false, 0, "force",
	0,
	"The tools analyse input files and reject files with invalid data"
	" structures. If --force is set, little repairable issues are ignored"
	" and a warning is printed.\n"
	"Option '--kmp force' does the same, but only for KMP files.\n"
	">>> THE RESULT MAY BE INVALID OUTPUT FILES! <<<"
    },

    {	OPT_REPAIR_MAGICS, true, false, false, false, false, 0, "repair-magics",
	"[=mode]",
	"Control the reparing of missing or wrong magics of files and"
	" sub-files by analysing file path and file extension. MODE is one of"
	" OFF (default), ANALYZE or REPAIR (default, if set without mode). OFF"
	" disables this feature, ANALYZE enables it for analysis only, and"
	" REPAIR repairs all magics while reading the files. Keyword FNAME can"
	" be appended (separated by a comma) to give filename scanning the"
	" highest priority.\n"
	">>> THE RESULT MAY BE INVALID OUTPUT FILES! <<<"
    },

    {	OPT_OLD, false, true, false, false, false, 0, "OLD",
	0,
	"Developer option: Cancel --NEW and use old implementation if"
	" available."
    },

    {	OPT_STD, false, true, false, false, false, 0, "STD",
	0,
	"Developer option: Cancel --OLD and --NEW and use standard"
	" implementation (default)."
    },

    {	OPT_NEW, false, true, false, false, false, 0, "NEW",
	0,
	"Developer option: Cancel --OLD and use new implementation if"
	" available."
    },

    {	OPT_EXTRACT, false, true, false, false, false, 0, "EXTRACT",
	0,
	"Create the directory and extract different objects in different"
	" formats at the moment when they are seen. This is a development"
	" helper option."
    },

    {0,0,0,0,0,0,0,0,0,0} // OPT__N_TOTAL == 61

};

//
///////////////////////////////////////////////////////////////////////////////
///////////////             alternate option infos              ///////////////
///////////////////////////////////////////////////////////////////////////////

static const InfoOption_t option_cmd_VERSION_BRIEF =
    {	OPT_BRIEF, false, false, false, false, false, 'B', "brief",
	0,
	"Print only the version number, revision and system. If set twice,"
	" print only the version number."
    };

static const InfoOption_t option_cmd_VERSION_LONG =
    {	OPT_LONG, false, false, false, false, false, 'l', "long",
	0,
	"Print in long format. Ignored if option --sections is set."
    };

static const InfoOption_t option_cmd_COLORS_LONG =
    {	OPT_LONG, false, false, false, false, false, 'l', "long",
	0,
	"Print also a list of all colored text types. If set twice, include"
	" alternative names. If set three times, include raw color names."
    };

static const InfoOption_t option_cmd_COLORS_BRIEF =
    {	OPT_BRIEF, false, false, false, false, false, 'B', "brief",
	0,
	"Ignore option --long and print a single status line about current"
	" color settings."
    };

static const InfoOption_t option_cmd_ERROR_LONG =
    {	OPT_LONG, false, false, false, false, false, 'l', "long",
	0,
	"Print message text instead of message name."
    };

static const InfoOption_t option_cmd_ERROR_BRIEF =
    {	OPT_BRIEF, false, false, false, false, false, 'B', "brief",
	0,
	"Print message number instead of message name."
    };

static const InfoOption_t option_cmd_FILETYPE_LONG =
    {	OPT_LONG, false, false, false, false, false, 'l', "long",
	0,
	"Print an additional column with the decompressed file type and"
	" version. If entered twice, a validation status column is added."
    };

static const InfoOption_t option_cmd_POINTS_BRIEF =
    {	OPT_BRIEF, false, false, false, false, false, 'B', "brief",
	0,
	"Print the table as comma separated lists in C notation."
    };

static const InfoOption_t option_cmd_POINTS_LONG =
    {	OPT_LONG, false, false, false, false, false, 'l', "long",
	0,
	"Append a string in --points format that defines the table. If set"
	" twice, append up to 3 strings in different modes."
    };

static const InfoOption_t option_cmd_EXTRACT_NO_HEADER =
    {	OPT_NO_HEADER, false, false, false, false, false, 'H', "no-header",
	0,
	"Exclude the section header from output."
    };


//
///////////////////////////////////////////////////////////////////////////////
///////////////                  CommandTab[]                   ///////////////
///////////////////////////////////////////////////////////////////////////////

static const KeywordTab_t CommandTab[] =
{
    { CMD_VERSION,	"VERSION",	0,		0 },
    { CMD_HELP,		"HELP",		"H",		0 },
    { CMD_HELP,		"?",		0,		0 },
    { CMD_ARGTEST,	"ARGTEST",	0,		0 },
    { CMD_TEST,		"TEST",		0,		0 },
    { CMD_COLORS,	"COLORS",	0,		0 },
    { CMD_ERROR,	"ERROR",	"ERR",		0 },
    { CMD_FILETYPE,	"FILETYPE",	"FT",		0 },
    { CMD_FILEATTRIB,	"FILEATTRIB",	"FA",		0 },
    { CMD_POINTS,	"POINTS",	"PTS",		0 },
    { CMD_REGEXP,	"REGEXP",	"RE",		0 },
    { CMD_EXTRACT,	"EXTRACT",	0,		0 },
    { CMD_SECTIONS,	"SECTIONS",	0,		0 },
    { CMD_LIST,		"LIST",		"LS",		0 },
    { CMD_LIST,		"LL",		0,		0 },
    { CMD_SLOTS,	"SLOTS",	0,		0 },
    { CMD_DIFF,		"DIFF",		"CMP",		0 },
    { CMD_CAT,		"CAT",		0,		0 },
    { CMD_MIX,		"MIX",		0,		0 },
    { CMD_IDENTIFIER,	"IDENTIFIER",	"ID",		0 },
    { CMD_IDENTIFIER,	"IDENTIFY",	0,		0 },
    { CMD_DECODE,	"DECODE",	"DEC",		0 },
    { CMD_ENCODE,	"ENCODE",	"ENC",		0 },
    { CMD_PATCH,	"PATCH",	"PAT",		0 },

    { CMD__N,0,0,0 }
};

//
///////////////////////////////////////////////////////////////////////////////
///////////////            OptionShort & OptionLong             ///////////////
///////////////////////////////////////////////////////////////////////////////

static const char OptionShort[] = "VhqvLc:lHBM:T:A:td:D:E:orupiP:1X";

static const struct option OptionLong[] =
{
	{ "version",		0, 0, 'V' },
	{ "help",		0, 0, 'h' },
	{ "xhelp",		0, 0, GO_XHELP },
	{ "allow-all",		0, 0, GO_ALLOW_ALL },
	 { "allowall",		0, 0, GO_ALLOW_ALL },
	{ "compatible",		1, 0, GO_COMPATIBLE },
	{ "width",		1, 0, GO_WIDTH },
	{ "quiet",		0, 0, 'q' },
	{ "verbose",		0, 0, 'v' },
	{ "logging",		0, 0, 'L' },
	{ "de",			0, 0, GO_DE },
	{ "colors",		2, 0, GO_COLORS },
	{ "no-colors",		0, 0, GO_NO_COLORS },
	 { "nocolors",		0, 0, GO_NO_COLORS },
	{ "ct-code",		0, 0, GO_CT_CODE },
	 { "ctcode",		0, 0, GO_CT_CODE },
	{ "le-code",		2, 0, GO_LE_CODE },
	 { "lecode",		2, 0, GO_LE_CODE },
	{ "chdir",		1, 0, GO_CHDIR },
	{ "const",		1, 0, 'c' },
	{ "long",		0, 0, 'l' },
	{ "no-header",		0, 0, 'H' },
	 { "noheader",		0, 0, 'H' },
	{ "brief",		0, 0, 'B' },
	{ "max-file-size",	1, 0, 'M' },
	 { "maxfilesize",	1, 0, 'M' },
	{ "tracks",		1, 0, 'T' },
	{ "arenas",		1, 0, 'A' },
	{ "points",		1, 0, GO_POINTS },
	 { "pts",		1, 0, GO_POINTS },
	{ "utf-8",		0, 0, GO_UTF_8 },
	 { "utf8",		0, 0, GO_UTF_8 },
	{ "no-utf-8",		0, 0, GO_NO_UTF_8 },
	 { "no-utf8",		0, 0, GO_NO_UTF_8 },
	 { "noutf8",		0, 0, GO_NO_UTF_8 },
	{ "test",		0, 0, 't' },
	{ "force",		0, 0, GO_FORCE },
	{ "repair-magics",	2, 0, GO_REPAIR_MAGICS },
	 { "repairmagics",	2, 0, GO_REPAIR_MAGICS },
	{ "OLD",		0, 0, GO_OLD },
	{ "STD",		0, 0, GO_STD },
	{ "NEW",		0, 0, GO_NEW },
	{ "EXTRACT",		0, 0, GO_EXTRACT },
	{ "dest",		1, 0, 'd' },
	{ "DEST",		1, 0, 'D' },
	{ "esc",		1, 0, 'E' },
	{ "overwrite",		0, 0, 'o' },
	{ "number",		0, 0, GO_NUMBER },
	 { "num",		0, 0, GO_NUMBER },
	{ "remove-dest",	0, 0, 'r' },
	 { "removedest",	0, 0, 'r' },
	 { "rm-dest",		0, 0, 'r' },
	 { "rmdest",		0, 0, 'r' },
	 { "remove",		0, 0, 'r' },
	{ "update",		0, 0, 'u' },
	{ "preserve",		0, 0, 'p' },
	{ "ignore",		0, 0, 'i' },
	{ "align",		1, 0, GO_ALIGN },
	{ "patch-bmg",		1, 0, 'P' },
	 { "patchbmg",		1, 0, 'P' },
	 { "pb",		1, 0, 'P' },
	 { "patch",		1, 0, 'P' },
	{ "macro-bmg",		1, 0, GO_MACRO_BMG },
	 { "macrobmg",		1, 0, GO_MACRO_BMG },
	 { "mb",		1, 0, GO_MACRO_BMG },
	{ "filter-bmg",		1, 0, GO_FILTER_BMG },
	 { "filterbmg",		1, 0, GO_FILTER_BMG },
	 { "fb",		1, 0, GO_FILTER_BMG },
	 { "msg",		1, 0, GO_FILTER_BMG },
	{ "endian",		1, 0, GO_BMG_ENDIAN },
	 { "bmg-endian",	1, 0, GO_BMG_ENDIAN },
	 { "bmgendian",		1, 0, GO_BMG_ENDIAN },
	{ "encoding",		1, 0, GO_BMG_ENCODING },
	 { "bmg-encoding",	1, 0, GO_BMG_ENCODING },
	 { "bmgencoding",	1, 0, GO_BMG_ENCODING },
	{ "inf-size",		1, 0, GO_BMG_INF_SIZE },
	 { "infsize",		1, 0, GO_BMG_INF_SIZE },
	 { "bmg-inf-size",	1, 0, GO_BMG_INF_SIZE },
	 { "bmginfsize",	1, 0, GO_BMG_INF_SIZE },
	{ "bmg-mid",		2, 0, GO_BMG_MID },
	 { "bmgmid",		2, 0, GO_BMG_MID },
	{ "force-attrib",	1, 0, GO_FORCE_ATTRIB },
	 { "forceattrib",	1, 0, GO_FORCE_ATTRIB },
	{ "def-attrib",		1, 0, GO_DEF_ATTRIB },
	 { "defattrib",		1, 0, GO_DEF_ATTRIB },
	{ "no-attrib",		0, 0, GO_NO_ATTRIB },
	 { "noattrib",		0, 0, GO_NO_ATTRIB },
	{ "x-escapes",		0, 0, GO_X_ESCAPES },
	 { "xescapes",		0, 0, GO_X_ESCAPES },
	{ "old-escapes",	0, 0, GO_OLD_ESCAPES },
	 { "oldescapes",	0, 0, GO_OLD_ESCAPES },
	{ "single-line",	0, 0, '1' },
	 { "singleline",	0, 0, '1' },
	{ "no-bmg-colors",	0, 0, GO_NO_BMG_COLORS },
	 { "nobmgcolors",	0, 0, GO_NO_BMG_COLORS },
	{ "bmg-colors",		0, 0, GO_BMG_COLORS },
	 { "bmgcolors",		0, 0, GO_BMG_COLORS },
	{ "no-bmg-inline",	0, 0, GO_NO_BMG_INLINE },
	 { "nobmginline",	0, 0, GO_NO_BMG_INLINE },
	{ "export",		0, 0, 'X' },
	{ "sections",		0, 0, GO_SECTIONS },

	{0,0,0,0}
};

//
///////////////////////////////////////////////////////////////////////////////
///////////////            OptionUsed & OptionIndex             ///////////////
///////////////////////////////////////////////////////////////////////////////

static u8 OptionUsed[OPT__N_TOTAL+1] = {0};

static const OptionIndex_t OptionIndex[UIOPT_INDEX_SIZE] =
{
	/* 0x000   */	 0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,
	/* 0x010   */	 0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,
	/* 0x020   */	 0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,
	/* 0x030   */	 0,
	/* 0x031 1 */	OPT_SINGLE_LINE,
	/* 0x032   */	 0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,
	/* 0x041 A */	OPT_ARENAS,
	/* 0x042 B */	OPT_BRIEF,
	/* 0x043   */	 0,
	/* 0x044 D */	OPT_DEST2,
	/* 0x045 E */	OPT_ESC,
	/* 0x046   */	 0,0,
	/* 0x048 H */	OPT_NO_HEADER,
	/* 0x049   */	 0,0,0,
	/* 0x04c L */	OPT_LOGGING,
	/* 0x04d M */	OPT_MAX_FILE_SIZE,
	/* 0x04e   */	 0,0,
	/* 0x050 P */	OPT_PATCH_BMG,
	/* 0x051   */	 0,0,0,
	/* 0x054 T */	OPT_TRACKS,
	/* 0x055   */	 0,
	/* 0x056 V */	OPT_VERSION,
	/* 0x057   */	 0,
	/* 0x058 X */	OPT_EXPORT,
	/* 0x059   */	 0,0,0,0, 0,0,0,0, 0,0,
	/* 0x063 c */	OPT_CONST,
	/* 0x064 d */	OPT_DEST,
	/* 0x065   */	 0,0,0,
	/* 0x068 h */	OPT_HELP,
	/* 0x069 i */	OPT_IGNORE,
	/* 0x06a   */	 0,0,
	/* 0x06c l */	OPT_LONG,
	/* 0x06d   */	 0,0,
	/* 0x06f o */	OPT_OVERWRITE,
	/* 0x070 p */	OPT_PRESERVE,
	/* 0x071 q */	OPT_QUIET,
	/* 0x072 r */	OPT_REMOVE_DEST,
	/* 0x073   */	 0,
	/* 0x074 t */	OPT_TEST,
	/* 0x075 u */	OPT_UPDATE,
	/* 0x076 v */	OPT_VERBOSE,
	/* 0x077   */	 0,0,0,0, 0,0,0,0, 0,
	/* 0x080   */	OPT_XHELP,
	/* 0x081   */	OPT_ALLOW_ALL,
	/* 0x082   */	OPT_COMPATIBLE,
	/* 0x083   */	OPT_WIDTH,
	/* 0x084   */	OPT_DE,
	/* 0x085   */	OPT_COLORS,
	/* 0x086   */	OPT_NO_COLORS,
	/* 0x087   */	OPT_CT_CODE,
	/* 0x088   */	OPT_LE_CODE,
	/* 0x089   */	OPT_CHDIR,
	/* 0x08a   */	OPT_POINTS,
	/* 0x08b   */	OPT_UTF_8,
	/* 0x08c   */	OPT_NO_UTF_8,
	/* 0x08d   */	OPT_FORCE,
	/* 0x08e   */	OPT_REPAIR_MAGICS,
	/* 0x08f   */	OPT_OLD,
	/* 0x090   */	OPT_STD,
	/* 0x091   */	OPT_NEW,
	/* 0x092   */	OPT_EXTRACT,
	/* 0x093   */	OPT_NUMBER,
	/* 0x094   */	OPT_ALIGN,
	/* 0x095   */	OPT_MACRO_BMG,
	/* 0x096   */	OPT_FILTER_BMG,
	/* 0x097   */	OPT_BMG_ENDIAN,
	/* 0x098   */	OPT_BMG_ENCODING,
	/* 0x099   */	OPT_BMG_INF_SIZE,
	/* 0x09a   */	OPT_BMG_MID,
	/* 0x09b   */	OPT_FORCE_ATTRIB,
	/* 0x09c   */	OPT_DEF_ATTRIB,
	/* 0x09d   */	OPT_NO_ATTRIB,
	/* 0x09e   */	OPT_X_ESCAPES,
	/* 0x09f   */	OPT_OLD_ESCAPES,
	/* 0x0a0   */	OPT_NO_BMG_COLORS,
	/* 0x0a1   */	OPT_BMG_COLORS,
	/* 0x0a2   */	OPT_NO_BMG_INLINE,
	/* 0x0a3   */	OPT_SECTIONS,
	/* 0x0a4   */	 0,0,0,0, 0,0,0,0, 0,0,0,0, 
	/* 0x0b0   */	 0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,
	/* 0x0c0   */	 0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,
	/* 0x0d0   */	 0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,
	/* 0x0e0   */	 0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,
	/* 0x0f0   */	 0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,
	/* 0x100   */	 0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,
	/* 0x110   */	 0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,
	/* 0x120   */	 0,0,0,0, 0,0,0,0, 0,0,0,0, 
};

//
///////////////////////////////////////////////////////////////////////////////
///////////////                opt_allowed_cmd_*                ///////////////
///////////////////////////////////////////////////////////////////////////////

static u8 option_allowed_cmd_VERSION[32] = // cmd #1
{
    0,1,0,1,0, 0,0,0,0,0,  0,0,0,0,0, 0,0,0,0,0,  0,0,0,0,0, 0,0,0,0,0,
    0,1
};

static u8 option_allowed_cmd_HELP[32] = // cmd #2
{
    1,1,1,1,1, 1,1,1,1,1,  1,1,1,1,1, 1,1,1,1,1,  1,1,1,1,1, 1,1,1,1,1,
    1,1
};

static u8 option_allowed_cmd_ARGTEST[32] = // cmd #3
{
    1,1,1,1,1, 1,1,1,1,1,  1,1,1,1,1, 1,1,1,1,1,  1,1,1,1,1, 1,1,1,1,1,
    1,1
};

static u8 option_allowed_cmd_TEST[32] = // cmd #4
{
    1,1,1,1,1, 1,1,1,1,1,  1,1,1,1,1, 1,1,1,1,1,  1,1,1,1,1, 1,1,1,1,1,
    1,1
};

static u8 option_allowed_cmd_COLORS[32] = // cmd #5
{
    0,1,0,1,0, 0,0,0,0,0,  0,0,0,0,0, 0,0,0,0,0,  0,0,0,0,0, 0,0,0,0,0,
    0,0
};

static u8 option_allowed_cmd_ERROR[32] = // cmd #6
{
    0,1,1,1,0, 0,0,0,0,0,  0,0,0,0,0, 0,0,0,0,0,  0,0,0,0,0, 0,0,0,0,0,
    0,1
};

static u8 option_allowed_cmd_FILETYPE[32] = // cmd #7
{
    0,1,0,0,0, 0,0,0,0,0,  0,0,1,0,0, 0,0,0,0,0,  0,0,0,0,0, 0,0,0,0,0,
    0,0
};

static u8 option_allowed_cmd_FILEATTRIB[32] = // cmd #8
{
    0,0,1,0,0, 0,0,0,0,0,  0,0,0,0,0, 0,0,0,0,0,  0,0,0,0,0, 0,0,0,0,0,
    0,0
};

static u8 option_allowed_cmd_POINTS[32] = // cmd #9
{
    0,1,0,1,0, 0,0,0,0,0,  0,0,0,0,0, 0,0,0,0,0,  0,0,0,0,0, 0,0,0,0,0,
    0,0
};

static u8 option_allowed_cmd_REGEXP[32] = // cmd #10
{
    0,0,0,0,0, 0,0,0,0,0,  0,0,0,0,0, 0,0,0,0,0,  0,0,0,0,0, 0,0,0,0,0,
    0,0
};

static u8 option_allowed_cmd_EXTRACT[32] = // cmd #11
{
    0,0,1,0,0, 0,0,0,0,0,  0,0,0,0,0, 0,0,0,0,0,  0,0,0,0,0, 0,0,0,0,0,
    0,0
};

static u8 option_allowed_cmd_SECTIONS[32] = // cmd #12
{
    0,0,0,0,0, 0,0,0,0,0,  0,0,1,0,0, 0,0,0,0,0,  0,0,0,0,0, 0,0,0,0,0,
    0,0
};

static u8 option_allowed_cmd_LIST[32] = // cmd #13
{
    0,0,0,0,0, 0,0,0,0,0,  0,0,1,0,1, 1,1,0,0,0,  0,0,0,0,0, 0,0,0,0,0,
    0,0
};

static u8 option_allowed_cmd_SLOTS[32] = // cmd #14
{
    0,0,0,0,0, 0,0,0,0,0,  0,0,1,0,1, 1,1,0,0,0,  0,0,0,0,0, 0,0,0,0,0,
    0,0
};

static u8 option_allowed_cmd_DIFF[32] = // cmd #15
{
    0,0,0,0,1, 0,1,0,0,0,  0,0,0,0,1, 1,1,0,0,0,  0,0,0,0,0, 0,0,0,0,0,
    0,0
};

static u8 option_allowed_cmd_CAT[32] = // cmd #16
{
    0,1,1,1,0, 0,0,0,0,0,  0,0,1,0,1, 1,1,1,1,1,  1,1,1,1,1, 1,1,1,1,1,
    1,0
};

static u8 option_allowed_cmd_MIX[32] = // cmd #17
{
    0,1,1,1,0, 0,0,0,0,0,  0,0,1,0,1, 1,1,1,1,1,  1,1,1,1,1, 1,1,1,1,1,
    1,0
};

static u8 option_allowed_cmd_IDENTIFIER[32] = // cmd #18
{
    0,1,1,1,0, 0,0,0,0,0,  0,0,0,0,0, 0,0,1,1,1,  1,1,1,1,1, 1,1,1,1,1,
    1,0
};

static u8 option_allowed_cmd_DECODE[32] = // cmd #19
{
    0,1,1,1,1, 1,1,1,1,1,  1,1,1,0,1, 1,1,1,1,1,  1,1,1,1,1, 1,1,1,1,1,
    1,0
};

static u8 option_allowed_cmd_ENCODE[32] = // cmd #20
{
    0,0,0,0,1, 1,1,1,1,1,  1,1,1,1,1, 1,1,1,1,1,  1,1,0,0,0, 0,0,0,0,0,
    0,0
};

static u8 option_allowed_cmd_PATCH[32] = // cmd #21
{
    0,1,1,1,1, 1,1,1,1,1,  1,1,1,1,1, 1,1,1,1,1,  1,1,1,1,1, 1,1,1,1,1,
    1,0
};


//
///////////////////////////////////////////////////////////////////////////////
///////////////                 InfoOption tabs                 ///////////////
///////////////////////////////////////////////////////////////////////////////

static const InfoOption_t * option_tab_tool[] =
{
	OptionInfo + OPT_VERSION,
	OptionInfo + OPT_HELP,
	OptionInfo + OPT_XHELP,
	OptionInfo + OPT_ALLOW_ALL,
	OptionInfo + OPT_COMPATIBLE,
	OptionInfo + OPT_WIDTH,
	OptionInfo + OPT_QUIET,
	OptionInfo + OPT_VERBOSE,
	OptionInfo + OPT_LOGGING,
	OptionInfo + OPT_DE,
	OptionInfo + OPT_COLORS,
	OptionInfo + OPT_NO_COLORS,
	OptionInfo + OPT_CT_CODE,
	OptionInfo + OPT_LE_CODE,
	OptionInfo + OPT_CHDIR,
	OptionInfo + OPT_CONST,
	OptionInfo + OPT_MAX_FILE_SIZE,
	OptionInfo + OPT_TRACKS,
	OptionInfo + OPT_ARENAS,
	OptionInfo + OPT_POINTS,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_TEST,
	OptionInfo + OPT_FORCE,
	OptionInfo + OPT_REPAIR_MAGICS,

	0
};

static const InfoOption_t * option_tab_cmd_VERSION[] =
{
	&option_cmd_VERSION_BRIEF,
	OptionInfo + OPT_SECTIONS,
	&option_cmd_VERSION_LONG,

	0
};

static const InfoOption_t * option_tab_cmd_HELP[] =
{
	OptionInfo + OPT_WIDTH,

	0
};

static const InfoOption_t * option_tab_cmd_ARGTEST[] =
{

	0
};

static const InfoOption_t * option_tab_cmd_TEST[] =
{

	0
};

static const InfoOption_t * option_tab_cmd_COLORS[] =
{
	OptionInfo + OPT_COLORS,
	OptionInfo + OPT_NO_COLORS,
	&option_cmd_COLORS_LONG,
	&option_cmd_COLORS_BRIEF,

	0
};

static const InfoOption_t * option_tab_cmd_ERROR[] =
{
	OptionInfo + OPT_SECTIONS,
	OptionInfo + OPT_NO_HEADER,
	&option_cmd_ERROR_LONG,
	&option_cmd_ERROR_BRIEF,

	0
};

static const InfoOption_t * option_tab_cmd_FILETYPE[] =
{
	&option_cmd_FILETYPE_LONG,
	OptionInfo + OPT_IGNORE,

	0
};

static const InfoOption_t * option_tab_cmd_FILEATTRIB[] =
{
	OptionInfo + OPT_NO_HEADER,

	0
};

static const InfoOption_t * option_tab_cmd_POINTS[] =
{
	OptionInfo + OPT_POINTS,
	&option_cmd_POINTS_BRIEF,
	&option_cmd_POINTS_LONG,

	0
};

static const InfoOption_t * option_tab_cmd_REGEXP[] =
{

	0
};

static const InfoOption_t * option_tab_cmd_EXTRACT[] =
{
	&option_cmd_EXTRACT_NO_HEADER,

	0
};

static const InfoOption_t * option_tab_cmd_SECTIONS[] =
{
	OptionInfo + OPT_IGNORE,

	0
};

static const InfoOption_t * option_tab_cmd_LIST[] =
{
	OptionInfo + OPT_IGNORE,
	OptionInfo + OPT_WIDTH,
	OptionInfo + OPT_PATCH_BMG,
	OptionInfo + OPT_MACRO_BMG,
	OptionInfo + OPT_FILTER_BMG,

	0
};

static const InfoOption_t * option_tab_cmd_SLOTS[] =
{
	OptionInfo + OPT_IGNORE,
	OptionInfo + OPT_WIDTH,
	OptionInfo + OPT_PATCH_BMG,
	OptionInfo + OPT_MACRO_BMG,
	OptionInfo + OPT_FILTER_BMG,

	0
};

static const InfoOption_t * option_tab_cmd_DIFF[] =
{
	OptionInfo + OPT_WIDTH,
	OptionInfo + OPT_PATCH_BMG,
	OptionInfo + OPT_MACRO_BMG,
	OptionInfo + OPT_FILTER_BMG,
	OptionInfo + OPT_DEST,
	OptionInfo + OPT_ESC,

	0
};

static const InfoOption_t * option_tab_cmd_CAT[] =
{
	OptionInfo + OPT_NO_HEADER,
	OptionInfo + OPT_BRIEF,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_BMG_ENDIAN,
	OptionInfo + OPT_BMG_ENCODING,
	OptionInfo + OPT_BMG_INF_SIZE,
	OptionInfo + OPT_BMG_MID,
	OptionInfo + OPT_FORCE_ATTRIB,
	OptionInfo + OPT_DEF_ATTRIB,
	OptionInfo + OPT_NO_ATTRIB,
	OptionInfo + OPT_X_ESCAPES,
	OptionInfo + OPT_OLD_ESCAPES,
	OptionInfo + OPT_SINGLE_LINE,
	OptionInfo + OPT_NO_BMG_COLORS,
	OptionInfo + OPT_BMG_COLORS,
	OptionInfo + OPT_NO_BMG_INLINE,
	OptionInfo + OPT_LONG,
	OptionInfo + OPT_EXPORT,
	OptionInfo + OPT_IGNORE,
	OptionInfo + OPT_PATCH_BMG,
	OptionInfo + OPT_MACRO_BMG,
	OptionInfo + OPT_FILTER_BMG,

	0
};

static const InfoOption_t * option_tab_cmd_MIX[] =
{
	OptionInfo + OPT_NO_HEADER,
	OptionInfo + OPT_BRIEF,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_BMG_ENDIAN,
	OptionInfo + OPT_BMG_ENCODING,
	OptionInfo + OPT_BMG_INF_SIZE,
	OptionInfo + OPT_BMG_MID,
	OptionInfo + OPT_FORCE_ATTRIB,
	OptionInfo + OPT_DEF_ATTRIB,
	OptionInfo + OPT_NO_ATTRIB,
	OptionInfo + OPT_X_ESCAPES,
	OptionInfo + OPT_OLD_ESCAPES,
	OptionInfo + OPT_SINGLE_LINE,
	OptionInfo + OPT_NO_BMG_COLORS,
	OptionInfo + OPT_BMG_COLORS,
	OptionInfo + OPT_NO_BMG_INLINE,
	OptionInfo + OPT_LONG,
	OptionInfo + OPT_EXPORT,
	OptionInfo + OPT_IGNORE,
	OptionInfo + OPT_PATCH_BMG,
	OptionInfo + OPT_MACRO_BMG,
	OptionInfo + OPT_FILTER_BMG,

	0
};

static const InfoOption_t * option_tab_cmd_IDENTIFIER[] =
{
	OptionInfo + OPT_LE_CODE,
	OptionInfo + OPT_CT_CODE,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_NO_HEADER,
	OptionInfo + OPT_BRIEF,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_BMG_ENDIAN,
	OptionInfo + OPT_BMG_ENCODING,
	OptionInfo + OPT_BMG_INF_SIZE,
	OptionInfo + OPT_BMG_MID,
	OptionInfo + OPT_FORCE_ATTRIB,
	OptionInfo + OPT_DEF_ATTRIB,
	OptionInfo + OPT_NO_ATTRIB,
	OptionInfo + OPT_X_ESCAPES,
	OptionInfo + OPT_OLD_ESCAPES,
	OptionInfo + OPT_SINGLE_LINE,
	OptionInfo + OPT_NO_BMG_COLORS,
	OptionInfo + OPT_BMG_COLORS,
	OptionInfo + OPT_NO_BMG_INLINE,
	OptionInfo + OPT_LONG,
	OptionInfo + OPT_EXPORT,

	0
};

static const InfoOption_t * option_tab_cmd_DECODE[] =
{
	OptionInfo + OPT_DEST,
	OptionInfo + OPT_DEST2,
	OptionInfo + OPT_ESC,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_OVERWRITE,
	OptionInfo + OPT_NUMBER,
	OptionInfo + OPT_REMOVE_DEST,
	OptionInfo + OPT_UPDATE,
	OptionInfo + OPT_PRESERVE,
	OptionInfo + OPT_NO_HEADER,
	OptionInfo + OPT_BRIEF,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_BMG_ENDIAN,
	OptionInfo + OPT_BMG_ENCODING,
	OptionInfo + OPT_BMG_INF_SIZE,
	OptionInfo + OPT_BMG_MID,
	OptionInfo + OPT_FORCE_ATTRIB,
	OptionInfo + OPT_DEF_ATTRIB,
	OptionInfo + OPT_NO_ATTRIB,
	OptionInfo + OPT_X_ESCAPES,
	OptionInfo + OPT_OLD_ESCAPES,
	OptionInfo + OPT_SINGLE_LINE,
	OptionInfo + OPT_NO_BMG_COLORS,
	OptionInfo + OPT_BMG_COLORS,
	OptionInfo + OPT_NO_BMG_INLINE,
	OptionInfo + OPT_LONG,
	OptionInfo + OPT_EXPORT,
	OptionInfo + OPT_IGNORE,
	OptionInfo + OPT_PATCH_BMG,
	OptionInfo + OPT_MACRO_BMG,
	OptionInfo + OPT_FILTER_BMG,

	0
};

static const InfoOption_t * option_tab_cmd_ENCODE[] =
{
	OptionInfo + OPT_DEST,
	OptionInfo + OPT_DEST2,
	OptionInfo + OPT_ESC,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_OVERWRITE,
	OptionInfo + OPT_NUMBER,
	OptionInfo + OPT_REMOVE_DEST,
	OptionInfo + OPT_UPDATE,
	OptionInfo + OPT_PRESERVE,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_BMG_ENDIAN,
	OptionInfo + OPT_BMG_ENCODING,
	OptionInfo + OPT_BMG_INF_SIZE,
	OptionInfo + OPT_BMG_MID,
	OptionInfo + OPT_FORCE_ATTRIB,
	OptionInfo + OPT_IGNORE,
	OptionInfo + OPT_PATCH_BMG,
	OptionInfo + OPT_MACRO_BMG,
	OptionInfo + OPT_FILTER_BMG,
	OptionInfo + OPT_ALIGN,

	0
};

static const InfoOption_t * option_tab_cmd_PATCH[] =
{
	OptionInfo + OPT_DEST,
	OptionInfo + OPT_DEST2,
	OptionInfo + OPT_ESC,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_OVERWRITE,
	OptionInfo + OPT_NUMBER,
	OptionInfo + OPT_REMOVE_DEST,
	OptionInfo + OPT_UPDATE,
	OptionInfo + OPT_PRESERVE,
	OptionInfo + OPT_NO_HEADER,
	OptionInfo + OPT_BRIEF,

	OptionInfo + OPT_NONE, // separator

	OptionInfo + OPT_BMG_ENDIAN,
	OptionInfo + OPT_BMG_ENCODING,
	OptionInfo + OPT_BMG_INF_SIZE,
	OptionInfo + OPT_BMG_MID,
	OptionInfo + OPT_FORCE_ATTRIB,
	OptionInfo + OPT_DEF_ATTRIB,
	OptionInfo + OPT_NO_ATTRIB,
	OptionInfo + OPT_X_ESCAPES,
	OptionInfo + OPT_OLD_ESCAPES,
	OptionInfo + OPT_SINGLE_LINE,
	OptionInfo + OPT_NO_BMG_COLORS,
	OptionInfo + OPT_BMG_COLORS,
	OptionInfo + OPT_NO_BMG_INLINE,
	OptionInfo + OPT_LONG,
	OptionInfo + OPT_EXPORT,
	OptionInfo + OPT_IGNORE,
	OptionInfo + OPT_PATCH_BMG,
	OptionInfo + OPT_MACRO_BMG,
	OptionInfo + OPT_FILTER_BMG,
	OptionInfo + OPT_ALIGN,

	0
};


//
///////////////////////////////////////////////////////////////////////////////
///////////////                   InfoCommand                   ///////////////
///////////////////////////////////////////////////////////////////////////////

static const InfoCommand_t CommandInfo[CMD__N+1] =
{
    {	0,
	false,
	false,
	false,
	"wbmgt",
	0,
	"wbmgt [option]... command [option|parameter|file]...",
	"Wiimms BMG Tool : Convert and patch raw and text BMG (message) files.",
	0,
	23,
	option_tab_tool,
	0
    },

    {	CMD_VERSION,
	false,
	false,
	false,
	"VERSION",
	0,
	"wbmgt VERSION [ignored]...",
	"Print program name and version and exit.",
	0,
	3,
	option_tab_cmd_VERSION,
	option_allowed_cmd_VERSION
    },

    {	CMD_HELP,
	false,
	false,
	false,
	"HELP",
	"H",
	"wbmgt HELP [--width=wd] OPT|OPTION ...\n"
	"wbmgt HELP [--width=wd] CMD|COMMAND [ignored]...\n"
	"wbmgt HELP [--width=wd] command [-b] [ignored]...\n"
	"wbmgt HELP [--width=wd] [ignored]...",
	"Print help for commands and options.",
	"Print help for commands and options.\n"
	"  The first variant (with keyword OPT or OPTION) prints a list of all"
	" global and command specific options. If at least one option is set,"
	" only info about the declared options are printed. The second variant"
	" (with keyword CMD or COMMAND) prints an overview about all commands."
	" The third variant (with a valid command name) prints details about"
	" the declared command. The fourth variant prints an overview about"
	" all commands and all global options.",
	1,
	option_tab_cmd_HELP,
	option_allowed_cmd_HELP
    },

    {	CMD_ARGTEST,
	false,
	false,
	false,
	"ARGTEST",
	0,
	"wbmgt ARGTEST ...",
	"This debug command accepts all kinds of parameters and prints one"
	" line for each parameter.",
	0,
	0,
	option_tab_cmd_ARGTEST,
	option_allowed_cmd_ARGTEST
    },

    {	CMD_TEST,
	false,
	false,
	false,
	"TEST",
	0,
	"wbmgt TEST [options]... [ignored]...",
	"This debugging command accepts all options and parameters and prints"
	" a list of the internal option values. The command is designed to"
	" test the option parameters. The non option parameters are completely"
	" ignored.",
	0,
	0,
	option_tab_cmd_TEST,
	option_allowed_cmd_TEST
    },

    {	CMD_COLORS,
	false,
	false,
	false,
	"COLORS",
	0,
	"wbmgt COLORS",
	"Ignore all parameters and print colored text for testing.",
	0,
	4,
	option_tab_cmd_COLORS,
	option_allowed_cmd_COLORS
    },

    {	CMD_ERROR,
	false,
	false,
	false,
	"ERROR",
	"ERR",
	"wbmgt ERROR [error_code]",
	"Translate an exit code to a message name. If no exit code is entered,"
	" print a table with all error messages.",
	0,
	4,
	option_tab_cmd_ERROR,
	option_allowed_cmd_ERROR
    },

    {	CMD_FILETYPE,
	false,
	false,
	false,
	"FILETYPE",
	"FT",
	"wbmgt FILETYPE file...",
	"Scan the header of the entered files and print file type and path for"
	" each file as list.",
	0,
	2,
	option_tab_cmd_FILETYPE,
	option_allowed_cmd_FILETYPE
    },

    {	CMD_FILEATTRIB,
	false,
	false,
	false,
	"FILEATTRIB",
	"FA",
	"wbmgt FILEATTRIB [keyword]...",
	"Print a table with attributes for all known file types. If at least"
	" one keyword is entered, only matching file types are printed. A"
	" keyword is either a file type (like 'BRRES' or 'BMG') or one of the"
	" printed keywords (like 'ARCHIVE' or 'EXTRACT').",
	0,
	1,
	option_tab_cmd_FILEATTRIB,
	option_allowed_cmd_FILEATTRIB
    },

    {	CMD_POINTS,
	false,
	false,
	false,
	"POINTS",
	"PTS",
	"wbmgt POINTS [--points=list]",
	"Print a table with the points assigned to player after a versus or"
	" room race.",
	0,
	3,
	option_tab_cmd_POINTS,
	option_allowed_cmd_POINTS
    },

    {	CMD_REGEXP,
	false,
	false,
	false,
	"REGEXP",
	"RE",
	"wbmgt REGEXP pattern string...",
	"Test implementation of regular expressions. PATTERN is the regular"
	" expression to find matches. Each STRING is object of the match and"
	" replace operation.",
	0,
	0,
	option_tab_cmd_REGEXP,
	option_allowed_cmd_REGEXP
    },

    {	CMD_EXTRACT,
	false,
	false,
	true,
	"EXTRACT",
	0,
	"wbmgt EXTRACT name source",
	"Extract BMG section NAME of file SOURCE and write the binary data to"
	" standard output. If NAME consists of less than 4 characters, then"
	" the first section that starts with these characters is dumped.",
	0,
	1,
	option_tab_cmd_EXTRACT,
	option_allowed_cmd_EXTRACT
    },

    {	CMD_SECTIONS,
	false,
	false,
	false,
	"SECTIONS",
	0,
	"wbmgt SECTIONS [source]...",
	"List all sections of each binary BMG file. Print offset, size, magic"
	" and a short info. If known, print number and size of elements too.",
	0,
	1,
	option_tab_cmd_SECTIONS,
	option_allowed_cmd_SECTIONS
    },

    {	CMD_LIST,
	false,
	false,
	false,
	"LIST",
	"LS",
	"wbmgt LIST [source]...",
	"List messages to proof the content. Patches are applied before"
	" listing. The lines are cut to fit the terminal width.",
	0,
	5,
	option_tab_cmd_LIST,
	option_allowed_cmd_LIST
    },

    {	CMD_SLOTS,
	false,
	false,
	false,
	"SLOTS",
	0,
	"wbmgt SLOTS [source]...",
	"Print a slot ordered list with slot number, message id, delta and"
	" attributes. Patches are applied before listing.",
	0,
	5,
	option_tab_cmd_SLOTS,
	option_allowed_cmd_SLOTS
    },

    {	CMD_DIFF,
	false,
	false,
	false,
	"DIFF",
	"CMP",
	"wbmgt DIFF source1 source2\n"
	"wbmgt DIFF source... --dest dest\n",
	"Compare two or more BMG (raw or text) files on string level and"
	" report mismatches for each string. If option --dest is set, then"
	" each source file is compared with a file in the destination. Patches"
	" are applied to all sources before comparing.",
	0,
	6,
	option_tab_cmd_DIFF,
	option_allowed_cmd_DIFF
    },

    {	CMD_CAT,
	false,
	false,
	true,
	"CAT",
	0,
	"wbmgt CAT [source]...",
	"Read the entered BMG files (text, binary or szs sub file) and print"
	" them as decoded text files to standard output. All BMG files of a"
	" single archive (SZS,...) are combined to 1 source. The output of all"
	" source files is concatenated.",
	0,
	21,
	option_tab_cmd_CAT,
	option_allowed_cmd_CAT
    },

    {	CMD_MIX,
	false,
	false,
	false,
	"MIX",
	0,
	"wbmgt MIX [source]...",
	"Read the entered BMG files (text, binary or szs sub file) and print"
	" them as decoded text files to standard output. All BMG files of all"
	" archives (SZS,...) are read. The output of all source files is"
	" combined and strings of later source files override prior defined"
	" strings.",
	0,
	21,
	option_tab_cmd_MIX,
	option_allowed_cmd_MIX
    },

    {	CMD_IDENTIFIER,
	false,
	false,
	false,
	"IDENTIFIER",
	"ID",
	"wbmgt IDENTIFIER",
	"Create a simple text BMG with the identifier message 3DEF only with"
	" respect to options --le-code and --ct-code. Print the result to"
	" standard output.",
	0,
	19,
	option_tab_cmd_IDENTIFIER,
	option_allowed_cmd_IDENTIFIER
    },

    {	CMD_DECODE,
	false,
	false,
	false,
	"DECODE",
	"DEC",
	"wbmgt DECODE [szs]...",
	"Read the entered message files and decode them to text files. All BMG"
	" files of a single archive (SZS,...) are concatenated to 1 source."
	" This command is similar to PATCH, but the result is always decoded."
	" The default destination is '%P/%N.txt'.",
	0,
	29,
	option_tab_cmd_DECODE,
	option_allowed_cmd_DECODE
    },

    {	CMD_ENCODE,
	false,
	false,
	false,
	"ENCODE",
	"ENC",
	"wbmgt ENCODE [source]...",
	"Read the entered message files and encode them to BMG files. All BMG"
	" files of a single archive (SZS,...) are concatenated to 1 source."
	" This command is similar to PATCH, but the result is always encoded."
	" The default destination is '%P/%N.bmg'.",
	0,
	18,
	option_tab_cmd_ENCODE,
	option_allowed_cmd_ENCODE
    },

    {	CMD_PATCH,
	false,
	false,
	false,
	"PATCH",
	"PAT",
	"wbmgt PATCH [source]...",
	"Patch the entered files by using the patch list specified by option"
	" --patch-bmg. The coding of the source files is not changed. The"
	" default destination is '%P/%F'.\n"
	"  Use 'wszst patch --patch-bmg ...' to patch BMG files within a SZS"
	" file.",
	0,
	30,
	option_tab_cmd_PATCH,
	option_allowed_cmd_PATCH
    },

    {0,0,0,0,0,0,0,0,0,0,0,0}
};

//
///////////////////////////////////////////////////////////////////////////////
///////////////                     InfoUI                      ///////////////
///////////////////////////////////////////////////////////////////////////////

const InfoUI_t InfoUI_wbmgt =
{
	"wbmgt",
	CMD__N,
	CommandTab,
	CommandInfo,
	OPT__N_SPECIFIC,
	OPT__N_TOTAL,
	OptionInfo,
	OptionUsed,
	OptionIndex,
	OptionShort,
	OptionLong
};

//
///////////////////////////////////////////////////////////////////////////////
///////////////                       END                       ///////////////
///////////////////////////////////////////////////////////////////////////////

