#LE-LPAR <<< The first 8 characters are the magic for a LE-CODE parameter file.
#        <<< Don't remove them!
#
###############################################################################
#
# This LE-CODE parameter file is a textual representation of the LPAR section
# of LE-CODE binary fils with editable parameters. It is defined by Wiimm.
#
# Hint:
#   Set one of the options --no-header (-H) or --brief (-B) while decoding
#   to suppress this general description. The --brief option will also disable
#   info parts in the different sections.
#
