
#FF#
###############################################################################

[AREA]
# Camera and other areas
# KMP/AREA syntax & semantics: https://szs.wiimm.de/doc/kmp/area

@REVISION        = %u
@AREA-HEAD-VALUE = %#x

#AREA#
#------------------------------------------------------------------------------
#       mode type    _____position/rotation/scale______   set-1  set-2
#  idx  came prio          x           y           z      route  enemy  ?@0x2e
#------------------------------------------------------------------------------
