
#FF#
###############################################################################

[AREA]
# Camera and other areas
# KMP/AREA syntax & semantics: https://szs.wiimm.de/doc/kmp/area

@REVISION        = %u
@AREA-HEAD-VALUE = %#x

#AREA#
#------------------------------------------------------------------------------------
#       mode type    _____position/rotation/scale______   _________settings_________
#  idx  came prio          x           y           z         #1     #2     #3     #4
#------------------------------------------------------------------------------------
