
#FF#
###############################################################################

[CAME]
# Cameras
# KMP/CAME syntax & semantics: https://szs.wiimm.de/doc/kmp/came

@REVISION        = %u
@OPENING-INDEX   = %s
@SELECTION-INDEX = %s

#CAME#
#-------------------------------------------------------------------------------------------
#  idx  type  v(came)  _________position (x,y,z)_________   zoom_beg  #        some
#       next  v(zoom)  _________rotation (x,y,z)_________   zoom_end  #     calculated
#     unknown v(v.pt)  ______view point beg (x,y,z)______       -     #       values
#      route  unknown  ______view point end (x,y,z)______    sec*60   #     (info only)
#-------------------------------------------------------------------------------------------
