# List of %u triangles

#D#
#-----------------------------------------+----------------------------------
# N0   _______ x,y,z of normal #0 _______ | flags (income -> current)
# N1   _______ x,y,z of normal #1 _______ | status
# N2   _______ x,y,z of normal #2 _______ | 'valid', 'used'
# N3   _______ x,y,z of normal #3 _______ |
# P1   _______ x,y,z of point #1 ________ | length
# P2   _______ x,y,z of point #2 ________ | difference: point2 - point1
# P3   _______ x,y,z of point #3 ________ | difference: point3 - point1
# LEN  _______ 3x side length2 __________ | area of triangle
# HT   _______ 3x height ________________ | min and max height
#-----------------------------------------+----------------------------------

