
#
#############
   [SETUP]
#############

# General setup.
# With the exception of section [TOOL], this must always be the first section.

#------------------------------------------------------------------------------

# Should the 10 battle arenas (slots 32-41) and 32 versus tracks (slots 0-31)
# be automatically defined with the original tracks? (0=NO/1=YES):
ORIG-BATTLE-ARENAS	= %s
ORIG-VERSUS-TRACKS	= %s

