
#------------------------------------------------------------------------------

[order]

# This list contains all extracted files in the order of the original archive.
# If creating archives (but not U8) this list will be used to sort the found
# files. For archives with directory support (all but not PACK) it is very
# important, that the directories are listed before the files that resides in
# the directories.
#
# The value before the equal sign is the file offset in the original archive
# and is ignored for sorting.

