
###############################################################################
#
# wszst settings:
# ---------------
#
# This is the settings file for wszst (tool of "Wiimms SZS Tools"). It
# was created by the EXTRACT command and is needed by the CREATE command
# to rebuild the original source archive with or without modifications.
# You can edit it, if you know what you do.
#
###############################################################################

# The first part contains some general settings:

