
#FF#
###############################################################################

[SETUP]
# This is the general setup and info section. Some parameters are preceeded by
# a hash ('#') to signal the informative only status. The scanning starts
# always with this section.

# Identify the tool and version, that have written this file:
TOOL     = %s
SYSTEM   = %s
VERSION  = %s
REVISION = %u
DATE     = %s

# The PAT version, number of sections and output mode. Info only.
PAT-VERSION = %2u
N-SECTIONS  = %2u
OUTPUT-MODE = %s

