#PAT  <<<  The first 4 characters '#PAT' are the magic for a PAT text file.
#     <<<  Don't remove them!
#
###############################################################################
#
# This is a textual representation of a PAT0 file used in Nintendos "Mario Kart
# Wii". "Wiimms SZS Tools" may convert binary (raw) and text PAT files in both
# directions in the near future. The text parser supports variables, C like
# expressions and nested IF-THEN-ELSE structures.
#
# Details about PAT text files are available in the Web:
#  - Parser Syntax and Semantics: https://szs.wiimm.de/doc/syntax
#  - PAT Syntax and Semantics:    https://szs.wiimm.de/doc/pat/text
#  - The BRRES/PAT0 file format:  https://szs.wiimm.de/r/wiki/PAT0
#
#------------------------------------------------------------------------------
