
#FF#
###############################################################################

[SETUP]
# This is the general setup and info section. Some parameters are preceeded by
# a hash ('#') to signal the informative only status. The scanning starts
# always with this section.

# Identify the tool and version, that have written this file:
TOOL     = %s
SYSTEM   = %s
VERSION  = %s
REVISION = %u
DATE     = %s

# The MDL name & version and the number of sections
@MDL-NAME    = "%s"
@MDL-VERSION = %2u
@N-SECTIONS  = %2u

