#MDL  <<<  The first 4 characters '#MDL' are the magic for a MDL text file.
#     <<<  Don't remove them!
#
###############################################################################
#
# This is a textual representation of a MDL file used in Nintendos "Mario Kart
# Wii". "Wiimms SZS Tools" may convert binary (raw) and text MDL files in both
# directions in the near future. The text parser supports variables, C like
# expressions and nested IF-THEN-ELSE structures.
#
# Info about the general parser syntax and semantics:
#   * https://szs.wiimm.de/doc/syntax
#
# Info about the MDL text syntax and semantics:
#   * https://szs.wiimm.de/doc/mdl/syntax
#
# Reference list of MDL parser functions:
#   * https://szs.wiimm.de/doc/mdl/func
#
# Info about the MDL file format:
#   * https://szs.wiimm.de/r/wiki/MDL0
#
# Hint:
#   Set one of the options --no-header (-H) or --brief (-B) while decoding
#   to suppress this large syntax info. The --brief option will also disable
#   info parts in the different sections.
