#CT-CODE

[INFO]
# This section will be ignored on scanning.

# This is a textual representation of CT-CODE file used by CTGPR made by Chadderz
# and MrBean3500vr. "Wiimms SZS Tools" can convert binary (raw) and text CT-CODE
# files in both directions. The text parser supports variables, C like expressions
# and nested IF-THEN-ELSE and LOOP structures.
#
# Info about the general parser syntax and semantics:
#   * https://szs.wiimm.de/doc/syntax
#
# Info about the CT-CODE:
#   * https://szs.wiimm.de/doc/ctcode
#
# Reference list of CT-CODE parser functions:
#   * https://szs.wiimm.de/doc/ctcode/func
#
# Hint:
#   Set the options --no-header (-H) while decoding to suppress this info and some
#   syntax descriptions below.

#----------------------------------------------------------------------------------
# Only the section [RACING-TRACK-LIST] is scanned, all other sections are ignored!
#----------------------------------------------------------------------------------

