[SETUP]

#--- Identify the tool and version, that have written this file:

TOOL     = %s
SYSTEM   = %s
VERSION  = %s
REVISION = %u
DATE     = %s


#--- mode

CT-MODE             = %3u # 1: CT-CODE, 2: LE-CODE


#--- Statistics

USED-RACING-CUPS    = %3u # number of active racing cups
MAX-RACING-CUPS     = %3u # max possible number of racing cups
USED-BATTLE-CUPS    = %3u # number of active battle cups
MAX-BATTLE-CUPS     = %3u # max possible number of battle cups

USED-RACING-TRACKS  = %3u # number of active racing tracks (used by cup)
USED-BATTLE-TRACKS  = %3u # number of active battle tracks (used by cup)
DEFINED-TRACKS      = %3u # total number of defined tracks
MAX-TRACKS          = %3u # total number of track slots

DEFINED-RACING-CUPS = %3u # number of defined racing cups
MAX-RACING-CUPS     = %3u # max possible number of racing cups
DEFINED-BATTLE-CUPS = %3u # number of defined battle cups
MAX-BATTLE-CUPS     = %3u # max possible number of battle cups
UNUSED-CUPS         = %3u # number of unused cups (space available)
