#KMG <<<  The first 4 characters are the magic for minigame.kmg text files.
#    <<<  Don't remove them!
#
#------------------------------------------------------------------------------
#
# This is the textual representation of an minigame.kmg file.
# It is defined by Wiimm and scanned by a 2-pass parser.
#
# Hints for decoding to a text file:
#
#  - If either option --no-header (-H) or option --brief (-B) is set, this
#    general description is suppressed.
#
#  - If either option --export (-X) is set once or option --brief (-B) is set
#    twice, a very small text file without descriptions and other not needed
#    parameters is created.
#
#  - If option --long (-l) is set, then additional hidden parameters are
#    included. They are automatically included, if they are differ from the
#    the standard settings.
#
# See http://wiki.tockdom.com/wiki/minigame.kmg for more details.
#
#------------------------------------------------------------------------------
